### ISSUE TITLE
1.3.0版本参数pageNum和pageSize传入0

### ISSUE THREAD

**Issue by gstsgy** [pagehelper/pagehelper-spring-boot#109]
本来想不要分页，结果一条数据出不来。之前版本好像没问题

**Comment by yiyingcanfeng** [comment]
`application.yml` 中现在需要明确指定 `page-size-zero` 为 `true` 才可以，应该是新版本默认值改成 `false` 了
```yml
pagehelper:
  page-size-zero: true
```

**Comment by gstsgy** [comment]
> `application.yml` 中现在需要明确指定 `page-size-zero` 为 `true` 才可以，应该是新版本默认值改成 `false` 了
> 
> ```yaml
> pagehelper:
>   page-size-zero: true
> ```

3q
