### ISSUE TITLE
1.3.1版本count问题

### ISSUE THREAD

**Issue by zhonghang1993** [pagehelper/pagehelper-spring-boot#121]
旧版本，在分页count统计个数时，是
`SELECT count(0) FROM ecg_project_assets dt WHERE dt.company_id = ? AND dt.deleted = 0 AND dt.project_id = ? `

1.3.1版本，在分页统计个数时，是：
`SELECT count(0) FROM (SELECT dt.id, dt.id, dt.english_name, dt.assents_img FROM adms_project_assets dt WHERE dt.deleted = 0 AND dt.project_id = ?) table_count`

问题：
但是1.3.1这种写法：count时将所有**查询参数带上了**，导致参数无法重复，必须要起别名而报错，如上面代码所示dt.id, dt.id这种写法就不支持了。但是1.2.10是支持的
`### Cause: java.sql.SQLSyntaxErrorException: Duplicate column name 'id'`

**Comment by Jnser** [comment]
同样的sql，使用1.3.0时的sql就是上面第一种，升级到1.4.6时sql就变成了第二种。不知道是否和版本有关系，如果没关系，那么作者所说的“sql包含特殊内容”，指的是哪类内容？麻烦解答下，感谢
