### ISSUE TITLE
springboot 2.6.0 pagehelper-spring-boot-starter 1.4.0 |||| The dependencies of some of the beans in the application context form a cycle

### ISSUE THREAD

**Issue by moeyj** [pagehelper/pagehelper-spring-boot#124]
***************************
APPLICATION FAILED TO START
***************************

Description:

The dependencies of some of the beans in the application context form a cycle:

┌──->──┐
|  com.github.pagehelper.autoconfigure.PageHelperAutoConfiguration
└──<-──┘

Action:

Relying upon circular references is discouraged and they are prohibited by default. Update your application to remove the dependency cycle between beans. As a last resort, it may be possible to break the cycle automatically by setting spring.main.allow-circular-references to true.

**Comment by ydq** [comment]
+1

**Comment by abel533** [comment]
问题已解决，晚上提交代码后发布新版本。

**Comment by moeyj** [comment]
> 問題已解決，晚上提交代碼後發布新版本。

喔，我早就在項目裏把你的api移除並修改升級了，也就花了不到1小時。
