### ISSUE TITLE
现有的版本好像与 SpringBoot 2.6.0 都不兼容

### ISSUE THREAD

**Issue by renfei** [pagehelper/pagehelper-spring-boot#126]
不仅仅是 1.4.0，我尝试了 1.3.1、1.3.0，都是一样的报错
```
ERROR 75953 --- [  restartedMain] o.s.b.d.LoggingFailureAnalysisReporter   : 

***************************
APPLICATION FAILED TO START
***************************

Description:

The dependencies of some of the beans in the application context form a cycle:

┌──->──┐
|  com.github.pagehelper.autoconfigure.PageHelperAutoConfiguration
└──<-──┘


Action:

Relying upon circular references is discouraged and they are prohibited by default. Update your application to remove the dependency cycle between beans. As a last resort, it may be possible to break the cycle automatically by setting spring.main.allow-circular-references to true.
```

关联问题：
- #124
- #125

**Comment by renfei** [comment]
@abel533 管理员大大请关注一下。

---

在 Spring Boot 2.6.0 变化还挺大的，默认完全禁止Bean的循环引用。

其他小伙伴想要临时解决这个问题可以设置：
```
spring.main.allow-circular-references = true
```

**Comment by kk-fan** [comment]
> 

设置过后直接停了
![image](https://user-images.githubusercontent.com/47165193/142991960-fa192e59-b793-4f09-aff3-37676781c5e3.png)

**Comment by kk-fan** [comment]
> @abel533管理员请关注一下。
> 
> 在 Spring Boot 2.6.0 变化还挺大的，默认完全禁止Bean的循环引用。
> 
> 其他小伙伴临时解决这个问题可以设置：
> 
> ```
> spring.main.allow-circular-references = true
> ```
设置之后启动不了
![image](https://user-images.githubusercontent.com/47165193/142992098-be712f3c-24f1-409c-b903-d290f8bdd9df.png)

**Comment by renfei** [comment]
> > @abel533管理员请关注一下。
> > 在 Spring Boot 2.6.0 变化还挺大的，默认完全禁止Bean的循环引用。
> > 其他小伙伴临时解决这个问题可以设置：
> > ```
> > spring.main.allow-circular-references = true
> > ```
> 
> 设置之后启动不了 ![图片](https://user-images.githubusercontent.com/47165193/142992098-be712f3c-24f1-409c-b903-d290f8bdd9df.png)

```spring.main.allow-circular-references``` 是我看报错信息里和官方文档里来的，参见：https://docs.spring.io/spring-boot/docs/current/reference/html/application-properties.html#application-properties.core.spring.main.allow-circular-references

>Whether to allow circular references between beans and automatically try to resolve them.

允许bean之间的循环引用并自动尝试解析它们，这也是 Spring Boot 2.6.0 中一大更新内容。

您的 Hikari 连接池为什么会关闭，我也不知道，我用的连接池是 Druid，是可以正常启动的。

**Comment by abel533** [comment]
问题已解决，晚上提交代码后发布新版本。
