### ISSUE TITLE
bug report

### ISSUE THREAD

**Issue by renjnet** [pagehelper/pagehelper-spring-boot#129]
返回列表为空时，传了一个值为33333的pageNum，返回数据pageNum及navigatePages不会自动置0。

`{"total":0,"list":[],"pageNum":33333,"pageSize":10,"size":0,"startRow":0,"endRow":0,"pages":0,"prePage":0,"nextPage":0,"isFirstPage":false,"isLastPage":true,"hasPreviousPage":true,"hasNextPage":false,"navigatePages":8,"navigatepageNums":[],"navigateFirstPage":0,"navigateLastPage":0}`

**Comment by abel533** [comment]
开启分页合理化了吗？
