### ISSUE TITLE
不知道为啥一直导入失败

### ISSUE THREAD

**Issue by luo353010979** [pagehelper/pagehelper-spring-boot#132]
Cannot resolve com.github.pagehelper:pagehelper-spring-boot-starter:pom:1.4.1 failed to transfer from https://repo.maven.apache.org/maven2 during a previous attempt. This failure was cached in the local repository and resolution is not reattempted until the update interval of central has elapsed or updates are forced. Original error: Could not transfer artifact com.github.pagehelper:pagehelper-spring-boot-starter:pom:1.4.1 from/to central (https://repo.maven.apache.org/maven2): transfer failed for https://repo.maven.apache.org/maven2/com/github/pagehelper/pagehelper-spring-boot-starter/1.4.1/pagehelper-spring-boot-starter-1.4.1.pom

**Comment by abel533** [comment]
国内用阿里云仓库试试
