### ISSUE TITLE
v1.4.2的版本yml文件中 pagehelper.page-size-zero 配置不生效

### ISSUE THREAD

**Issue by SupermanChao** [pagehelper/pagehelper-spring-boot#134]
初步试了下，`v1.4.1` 和 `v1.4.2`版本里面，yml文件里面的如下配置不生效
```
pagehelper:
  page-size-zero: true
```
从查完数据库返回的`Page`对象上调用`getPageSizeZero()`返回的一直都是`false`，而且也没有达到查全部的效果
试了下`v1.4.0`和`v1.3.1`上是好的
辛苦作者排查下

**Comment by Sddft97** [comment]
我也遇到了这个问题，`v1.4.2`版本的这一项配置无效。
我调用`getPageSizeZero()`会直接返回null（Boolean包装类），从日志上可以看到其实没有真正的执行查询语句，所以查询的结果也是空的。
我的解决方案是，在`startPage()`的时候传参指定`pageSizeZero`为true，即
```java
PageHelper.startPage(1, 0, true, true, true);
```

这样可以查询全部数据，但是这种方式有些难受，辛苦作者排查下yml配置注入失效的问题吧。

**Comment by abel533** [comment]
1.4.4 已发布，已支持。
