### ISSUE TITLE
有关配置属性取值的疑惑！

### ISSUE THREAD

**Issue by wwm0104** [pagehelper/pagehelper-spring-boot#14]
1、在spring-configuration-metadata.json 里面 name值是pagehelper.support-methods-arguments
{
      "sourceType": "com.github.pagehelper.autoconfigure.PageHelperProperties",
      "name": "pagehelper.support-methods-arguments",
      "type": "java.lang.String"
    }

2.为什么在PageHelperProperties 中 取值的时候 怎么是这个
this.properties.getProperty("supportMethodsArguments");

**Comment by abel533** [comment]
spring boot 支持relax property，就是符合要求的属性名都代表的同一个。

**Comment by wwm0104** [comment]
谢谢你的解答！！
