### ISSUE TITLE
新版本pagehelper配置失效

### ISSUE THREAD

**Issue by nian5241** [pagehelper/pagehelper-spring-boot#145]
version：com.github.pagehelper:pagehelper-spring-boot-starter:1.4.2

detail:最近升级pagehelper版本之后发现pagehelper的配置失效了。看了下源代码发现PageHelperProperties这个配置类修改成了继承Properties，本身的set方法一个都没执行到，属性名带中划线的不会转成驼峰了，从而导致带中划线的配置全都失效了。
请尽快修复吧。

**Comment by nian5241** [comment]
验证好了吗

**Comment by abel533** [comment]
1.4.4 已发布。
