### ISSUE TITLE
吃掉 order by

### ISSUE THREAD

**Issue by MaiJiantian** [pagehelper/pagehelper-spring-boot#147]
application.yml能否增加可配置项，优化count开关，在某些场景下，order by不能省略，每次使用/**/注释不优雅，如果直接配置关掉count，那么又会出现新的问题，total 有时会 = -1 ，可实际是有数据的

**Comment by abel533** [comment]
某些场景如何配置？可以提供一个方案讨论一下。

**Comment by MaiJiantian** [comment]
鄙见认为子查询中含有排序，那么不应该去掉

**Comment by abel533** [comment]
`keepSubQueryOrderBy: false|true`

**Comment by abel533** [comment]
19. `keepOrderBy`：转换count查询时保留查询的 order by 排序。除全局配置外，可以针对单次操作进行设置。

20. `keepSubSelectOrderBy`：转换count查询时保留子查询的 order by 排序。可以避免给所有子查询添加 `/*keep orderby*/`，除全局配置外，可以针对单次操作进行设置。
