### ISSUE TITLE
通过pagehelper实现较个性化的分页需求

### ISSUE THREAD

**Issue by xiaodd411** [pagehelper/pagehelper-spring-boot#162]
如何通过分页插件pagehelper自定义分页需求如第一页大小与后面页大小不一样,怎么实现页码,以及每页的数据不会丢失(正常情况下会将第一页后两个数据丢失)

**Comment by xiaodd411** [comment]
我使用开启分页返回的对象进行自定义设置的话返回的对象是空

**Comment by abel533** [comment]
自己拿到total后根据自己需求计算，用自定义PageInfo.
