### ISSUE TITLE
springboot使用1.4.7版本后启动报错

### ISSUE THREAD

**Issue by Charlee-du** [pagehelper/pagehelper-spring-boot#165]
使用1.4.4版本启动正常。但是往上升级就使用不了。启动报错。例如1.4.7版本报错信息如下：

2023-09-04 23:36:57.543 ERROR 15090 --- [           main] o.s.b.d.LoggingFailureAnalysisReporter   : 

***************************
APPLICATION FAILED TO START
***************************

Description:

Field appService in com.cloudggy.system.controller.SysAppController required a single bean, but 2 were found:
	- sysAppServiceImpl: defined in file [/Users/geruixue/IdeaProjects/cloudggy_cloud/cloudggy-modules/cloudggy-system/target/classes/com/cloudggy/system/service/impl/SysAppServiceImpl.class]
	- ISysAppService: defined in file [/Users/geruixue/IdeaProjects/cloudggy_cloud/cloudggy-modules/cloudggy-system/target/classes/com/cloudggy/system/service/ISysAppService.class]

Action:

Consider marking one of the beans as @Primary, updating the consumer to accept multiple beans, or using @Qualifier to identify the bean that should be consumed

**Comment by abel533** [comment]
看着像spring boot版本变化带来的，和分页插件不一定有关系。。你spring boot版本是如何指定的？出错时版本是否有变化？
