### ISSUE TITLE
PageInterceptor注册两次bug

### ISSUE THREAD

**Issue by wang-laoshi** [pagehelper/pagehelper-spring-boot#18]
我最早用pagehelper-spring-boot-starter的时候，在mybatis里里住了一个plugin（PageInterceptor），在debug时发现这个PageInterceptor被注册了两次。
        if(ms.getId().endsWith(MSUtils.COUNT)){
            throw new RuntimeException("在系统中发现了多个分页插件，请检查系统配置!");
        }
        

以至于第二次运行的时候，由于第一次已经更改了sql_id，第二次会在这里报一个异常
解决方法有两个
一：去掉mybatis.xml里的plugin注册，这样系统会默认注册一个，但是这样就带来了问题，在单元测试的时候，由于没有加载spring-boot，会导致一个intercepter都没有被注册上，单测和实际运行不匹配
解决方法二：将
pagehelper-spring-boot-starter换成普通的pagehelper，这样可以保证单测和web环境运行效果一样

so，我觉得pagehelper-spring-boot-starter这里是个bug，希望能有人反馈一下

**Comment by abel533** [comment]
抛异常是为了提醒这种潜在的错误，起始还可以增加个参数控制注册多次时，抛出异常或者跳过后面的分页插件。

**Comment by xmanOxman** [comment]
我使用pagehelper-spring-boot-autoconfigure-1.2.3  也出现这个问题。在springboot启动类中添加了排除后正常了：
@SpringBootApplication(exclude = PageHelperAutoConfiguration.class)

**Comment by promise2mm** [comment]
@xmanOxman 用你的方法解决了，在启动类排除了PageHelperAutoConfiguration
用的是1.2.5版本
