### ISSUE TITLE
pageInfo的total属性是当前页记录数，如何配置使total设置成总记录数

### ISSUE THREAD

**Issue by youapple** [pagehelper/pagehelper-spring-boot#21]

**Comment by abel533** [comment]
total 是总记录数，不是当前页。

**Comment by duweili** [comment]
![image](https://user-images.githubusercontent.com/22166614/34135429-9de815a0-e49b-11e7-9ad4-fd2852284335.png)

SELECT count(0) FROM T
值为3，但是结果中的total显示的是我的当前分页的记录数，这个要怎样设置？谢谢大神！

**Comment by abel533** [comment]
@duweili SQL日志有没有检查过？确定经过分页了吗？

**Comment by duxiaolong** [comment]
@duweili 这个问题解决了吗？我这里也是这个问题，检查打印的sql，确认分页了。但是total是当前页的记录数。

**Comment by duxiaolong** [comment]
@abel533 配置文件配置方言就好了。
pagehelper.dialect=com.github.pagehelper.dialect.helper.OracleDialect
但是，配置方言以后，列表就没有分页了。

**Comment by hanzhenchaoGit** [comment]
@duweili 我也是这个问题 同问

**Comment by hanzhenchaoGit** [comment]
@duxiaolong 用了dubbo了是吗  我这个问题解决了  分页没有问题了

**Comment by huzhixiang** [comment]
怎么解决呢？加了dialect: com.github.pagehelper.dialect.helper.MySqlDialect，就不分页了
{
  "code": 1,
  "msg": "成功",
  "data": {
    "pageNum": 1,
    "pageSize": 18,
    "size": 18,
    "startRow": 0,
    "endRow": 17,
    "total": 18,
    "pages": 1,

**Comment by abel533** [comment]
@huzhixiang 不应该配置 dialect，应该是 helperDialect，文档有说明。

**Comment by githupwangyu** [comment]
无轮子妈设置都不能分页，一直都是总的数据，分页不生效

**Comment by githupwangyu** [comment]
无论怎么修改配置，查询总是全部数据，拦截不生效（springboot的使用）

**Comment by GithubXie40** [comment]
遇到同样的问题，total无论任何都与当前页的记录数(list.siez())一样，而不是总记录数。如何解决？
（使用情况：直接引入starter，没有做任何配置）

**Comment by GithubXie40** [comment]
遇到同样的问题，各种配置无果后，发现代码写的有问题。
解决方案：
Page<T> page = PageHelper.startPage(xx,xx);
// todo:your query
PageInfo<T> pageInfo = new PageInfo<>(page); 
！！！重点这里：page 参数一定要传Page的实例，才会得到正确的total，传List的实例会调用size();

**Comment by abel533** [comment]
@GithubXie40 不是你说的这样，通过分页插件处理后的结果，表面上是 List 类型，实际是 Page( `extends ArrayList`)。只有不是经过分页，或者你自己对结果处理后再用 PageInfo，才没有 total。

注意 java8 lambda 处理后的流会丢失分页信息。

**Comment by logicjwell** [comment]
`
List<RequirementObj> requirementObjs= requirement.getRequirements(currentPage,pageSize);
        PageInfo<RequirementObj> origPageInfo = new PageInfo<>(requirementObjs);

        List<BaseRequirementResp> baseRequirementResps = requirementObjs.stream().map(o-> new BaseRequirementResp(o)).collect(Collectors.toList());

        PageInfo<BaseRequirementResp> pageInfo = new PageInfo<>(baseRequirementResps);
        BeanUtils.copyProperties(origPageInfo,pageInfo,"list");
`

**Comment by zxksunflower** [comment]
哈哈哈......

**Comment by smfx1314** [comment]
我的也是total总是等于pageSize，如果使用lamada的话，数据确实会丢失

**Comment by slyang520** [comment]
怎么解  我也遇到了

**Comment by SanJingYe88** [comment]
> 在lambda之前，先搞一个pageinfo, lambda之后，把分页信息copy进去 @
> 
> `
> List requirementObjs= requirement.getRequirements(currentPage,pageSize);
> PageInfo origPageInfo = new PageInfo<>(requirementObjs);
> 
> ```
>     List<BaseRequirementResp> baseRequirementResps = requirementObjs.stream().map(o-> new BaseRequirementResp(o)).collect(Collectors.toList());
> 
>     PageInfo<BaseRequirementResp> pageInfo = new PageInfo<>(baseRequirementResps);
>     BeanUtils.copyProperties(origPageInfo,pageInfo,"list");
> ```
> 
> `
这样可以用, 结果没问题
