### ISSUE TITLE
是否能发布一个版本,依赖于tk.mapper的版本?

### ISSUE THREAD

**Issue by cuisongliu** [pagehelper/pagehelper-spring-boot#30]
RT,因为好多插件还是用的tk的相关的，使用了mapper starter 1.2.1 去掉了mybatis的官方starter ,是否pageHelper能与其保持一直?

**Comment by abel533** [comment]
1.2.1 可以和官方 starter 共存，不影响分页插件，分页插件和通用Mapper都是独立的，不会互相依赖。

**Comment by cuisongliu** [comment]
我引用了tk.mapper，我用分页的时候是不是可以把官方的starter 移除依赖了?

**Comment by abel533** [comment]
先别着急移除。。等我测试完分页stater再决定。
