### ISSUE TITLE
spring boot 1.5.1.RELEASE集成pagehelper-spring-boot-starter 1.2.3启动报错

### ISSUE THREAD

**Issue by tsaimn** [pagehelper/pagehelper-spring-boot#34]
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'com.github.pagehelper.autoconfigure.PageHelperAutoConfiguration': Invocation of init method failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'pageHelperProperties': Could not bind properties to Properties (prefix=pagehelper, ignoreInvalidFields=false, ignoreUnknownFields=true, ignoreNestedProperties=false); nested exception is java.lang.IllegalStateException: Invalid target for Validator [org.springframework.boot.context.properties.ConfigurationPropertiesBindingPostProcessor$ValidatedLocalValidatorFactoryBean@7bbcf6f0]: org.springframework.boot.bind.RelaxedDataBinder$MapHolder@2b80e5a9

切换至spring boot 1.5.1.RELEASE可以正常启动

**Comment by abel533** [comment]
切换至spring boot 1.5.1.RELEASE可以正常启动 ？ 哪个版本不能用？

**Comment by tsaimn** [comment]
切换至spring boot 1.5.9.RELEASE可以正常启动

**Comment by abel533** [comment]
特地换了几个版本试了试，只有 1.5.0 和 1.5.1 版本有问题，建议别用这俩版本，其他都没问题。
