### ISSUE TITLE
分模块项目中pagehelper不起作用

### ISSUE THREAD

**Issue by mikumy-dev** [pagehelper/pagehelper-spring-boot#37]
在不分模块的项目中，即所有的dao, pojo, mapper, service, controller等都放在一个project里面，pagehelper可以正常使用。而把一个project分成几个project的时候，pagehelper就不起作用了。

环境：
spring, 5.0.2.RELEASE;
mybatis, 3.4.5;
pagehelper, 5.1.2;

项目分为4个模块，分别是
Admin模块（maven web项目，用于写管理员相关权限）
API模块（maven web项目，用于写各种接口，放有Controller）
Data模块（maven web项目，用于操作数据库，放有dao, mapper, serviceImpl, mybatis配置文件，已配置pageHelper）
Common模块（maven项目，上面3个项目依赖于此项目，放有pojo，service）

位于API模块的Controller里面的如下两句代码，不能起到分页的作用：
<pre><code>PageHelper.startPage(currentPage, pageSize);
List&lt;TbProduct&gt; list = productService.selectByShopIdAndType(shopId, type, searchText);
</code></pre>
传入参数为<pre><code>
{
	"currentPage":1,//当前页码
	"pageSize":5,//每页显示条数
	"searchText":"",//搜索内容
	"shopId":1, //门店ID
	"type":null //产品类型，可选
}</code></pre>
Data模块中TbProductMapper.xml对应的sql语句为<pre>
select 
    &lt;include refid="Base_Column_List" /&gt;    
    from tb_product
    where is_del = 0 and shop_id = #{shopId,jdbcType=INTEGER} 
    &lt;if test="type!=null and type!=0"&gt;
    and type = #{type,jdbcType=INTEGER}
    &lt;/if&gt;
    &lt;if test="searchText != null or searchText!=''"&gt;
    and name like concat('%',#{searchText,jdbcType=VARCHAR},'%')
    &lt;/if&gt;</pre>

数据库共14条数据，本该传回前5条，却一下子传回14条数据。求解。

**Comment by abel533** [comment]
分页要写到Service层，紧跟在要调用的dao方法前。否则容易引起意外，具体看这里：
>https://github.com/pagehelper/Mybatis-PageHelper/blob/master/wikis/zh/HowToUse.md#3-pagehelper-%E5%AE%89%E5%85%A8%E8%B0%83%E7%94%A8

如果想Controller中直接这么操作，就用参数方式。
