### ISSUE TITLE
pagehelper-spring-boot-starter自动配置后自定义其他mybatis拦截器不起作用，不执行intercept方法

### ISSUE THREAD

**Issue by zgmgt** [pagehelper/pagehelper-spring-boot#39]
引入pagehelper starter
<dependency>
    <groupId>com.github.pagehelper</groupId>
    <artifactId>pagehelper-spring-boot-starter</artifactId>
    <version>1.2.4</version>
</dependency>
自己定义的Interceptor如下

@Intercepts({ @Signature(type = Executor.class, method = "update", args = { MappedStatement.class, Object.class }),
		@Signature(type = Executor.class, method = "query", args = { MappedStatement.class, Object.class,
				RowBounds.class, ResultHandler.class }) })
@Component
@AutoConfigureAfter(PageHelperAutoConfiguration.class)
public class MyInterceptor implements Interceptor {

	private Properties properties = null;

	public Object intercept(Invocation invocation) throws Throwable {
		System.out.println("###########################-interceptor");
		Object[] args = invocation.getArgs();
		MappedStatement ms = (MappedStatement) args[0];
		BoundSql bsql = ms.getBoundSql(args[1]);
		Method method = invocation.getMethod();
		Object target = invocation.getTarget();
		return invocation.proceed();
	}

	public Object plugin(Object target) {
		System.out.println("########################-plugin " + target);
		return Plugin.wrap(target, this);
	}

	public void setProperties(Properties properties) {
		this.properties = properties;
		System.out.println("##############-properties " + this.properties);
	}
}
它始终不执行intercept方法，只会执行plugin方法，当我去掉pagehelper starter的pom依赖，它就会执行，感觉不知道冲突在哪里。。。

**Comment by abel533** [comment]
冲突在这里：https://github.com/pagehelper/Mybatis-PageHelper/blob/master/wikis/zh/Interceptor.md

**Comment by zgmgt** [comment]
谢谢，回头我试试.太感谢了

**Comment by zgmgt** [comment]
这边按照那个方式使用ok了。。O(∩_∩)O谢谢
