### ISSUE TITLE
PageHelper spring boot  引入后报错问题

### ISSUE THREAD

**Issue by luckypolaris** [pagehelper/pagehelper-spring-boot#40]
如果是自定义的 datasource (例如使用mycat)  并且是自己写的datasource AutoConfig 
没用 pagehelper-spring-boot-start时 正常使用。
引入start后，会报如下错误，怎么破？

***************************
APPLICATION FAILED TO START
***************************

Description:

Cannot determine embedded database driver class for database type NONE

Action:

If you want an embedded database please put a supported one on the classpath. If you have database settings to be loaded from a particular profile you may need to active it

**Comment by abel533** [comment]
jdbcurl 怎么配置的？

**Comment by alexccpg** [comment]
不引入starter包    把PageHelperAutoConfiguration这个类的代码拷贝出来，注释掉@ConditionalOnBean(SqlSessionFactory.class) 就不报错了，不知道什么原因
`@Configuration
//@ConditionalOnBean(SqlSessionFactory.class)
@EnableConfigurationProperties(PageHelperProperties.class)
public class PageHelperAutoConfig{

        @Autowired
        private List<SqlSessionFactory> sqlSessionFactoryList;

        @Autowired
        private PageHelperProperties properties;

        /**
         * 接受分页插件额外的属性
         *
         */
        @Bean
        @ConfigurationProperties(prefix = PageHelperProperties.PAGEHELPER_PREFIX)
        public Properties pageHelperProperties() {
                return new Properties();
        }

        @PostConstruct
        public void addPageInterceptor() {
                PageInterceptor interceptor = new PageInterceptor();
                Properties properties = new Properties();
                //先把一般方式配置的属性放进去
                properties.putAll(pageHelperProperties());
                //在把特殊配置放进去，由于close-conn 利用上面方式时，属性名就是 close-conn 而不是 closeConn，所以需要额外的一步
                properties.putAll(this.properties.getProperties());
                interceptor.setProperties(properties);
                for (SqlSessionFactory sqlSessionFactory : sqlSessionFactoryList) {
                        sqlSessionFactory.getConfiguration().addInterceptor(interceptor);
                }
        }
}`

**Comment by abel533** [comment]
这种情况只能针对代码调试找原因了。

**Comment by tianriver** [comment]
我也碰到这个问题了，我用的是sharding sphere。在application.yml中并没有配置spring.datasource，配置的是spring.shardingsphere.datasource。//@ConditionalOnBean(SqlSessionFactory.class)就行了

**Comment by ChenTT5** [comment]
> 如果是自定义的 datasource (例如使用mycat) 并且是自己写的datasource AutoConfig
> 没用 pagehelper-spring-boot-start时 正常使用。
> 引入start后，会报如下错误，怎么破？
> 
> APPLICATION FAILED TO START
> 
> Description:
> 
> Cannot determine embedded database driver class for database type NONE
> 
> Action:
> 
> If you want an embedded database please put a supported one on the classpath. If you have database settings to be loaded from a particular profile you may need to active it

其实是Configuration加载顺序的问题，你自己定义的starter中的Configuration加载在PageHepler的Configuration之后了，造成了SpringBoot先加载了自己的DS 的Configuration，所以报错。在你自己的Configuration中加上@AutoConfigureBefore(DataSourceAutoConfiguration.class)这个就OK了。
