### ISSUE TITLE
执行count，不执行查询

### ISSUE THREAD

**Issue by QJBChou** [pagehelper/pagehelper-spring-boot#55]
public PageInfo<BrandInfoForm> queryList(BrandInfoForm form, PageSearchVo pageSearchVo) {

       System.err.println(">>>>"+JSON.toJSONString(form)+">>>>"+JSON.toJSONString(pageSearchVo));

        System.err.println(pageSearchVo.getPage().intValue() + 1 +"&&&&"+ pageSearchVo.getSize());

        **PageHelper.startPage(pageSearchVo.getPage().intValue() + 1, pageSearchVo.getSize());**

        List<BrandInfoForm> brandInfoFormList = brandInfoFormMapper.queryList(form);

        System.err.println("----"+JSON.toJSONString(brandInfoFormList));

**Comment by QJBChou** [comment]
![image](https://user-images.githubusercontent.com/38748326/46070396-49b7fe80-c1b0-11e8-8e4c-b4a4c295059a.png)

**Comment by CarlWangShuLin** [comment]
请问这个问题解决了么？

**Comment by abel533** [comment]
count结果是0的时候就不执行查询了。
