### ISSUE TITLE
分页不起作用

### ISSUE THREAD

**Issue by 84yy** [pagehelper/pagehelper-spring-boot#57]
尝试自己解决2天未果.求教大佬,以下为问题描述:

Spring-boot是1.5.4版本
pagehelper-spring-boot-starter 从1.0到1.2.9都试过了还是不行.

**依赖如下:**

    <dependencies>
        <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-lang3</artifactId>
            <version>3.3.2</version>
        </dependency>

        <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-io</artifactId>
            <version>1.3.2</version>
        </dependency>
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-beans</artifactId>
            <version>4.3.4.RELEASE</version>
        </dependency>

        <dependency>
            <groupId>tk.mybatis</groupId>
            <artifactId>mapper-spring-boot-starter</artifactId>
            <version>1.2.3</version>
        </dependency>

        <dependency>
            <groupId>org.mybatis.spring.boot</groupId>
            <artifactId>mybatis-spring-boot-starter</artifactId>
            <version>1.2.0</version>
        </dependency>

        <dependency>
            <groupId>com.github.pagehelper</groupId>
            <artifactId>pagehelper-spring-boot-starter</artifactId>
            <version>1.2.9</version>
        </dependency>

        
            
            
            
        
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-beans</artifactId>
            <version>4.3.4.RELEASE</version>
        </dependency>
        
            
            
            
        

        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-web</artifactId>
            <version>4.3.9.RELEASE</version>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-log4j2</artifactId>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.dataformat</groupId>
            <artifactId>jackson-dataformat-yaml</artifactId>
        </dependency>
        <dependency>
            <groupId>io.jsonwebtoken</groupId>
            <artifactId>jjwt</artifactId>
            <version>0.7.0</version>
        </dependency>
        <dependency>
            <groupId>joda-time</groupId>
            <artifactId>joda-time</artifactId>
            <version>2.9.5</version>
        </dependency>
        <dependency>
            <groupId>javax.servlet</groupId>
            <artifactId>javax.servlet-api</artifactId>
            <version>3.1.0</version>
        </dependency>
        <dependency>
            <groupId>de.schlichtherle.truelicense</groupId>
            <artifactId>truelicense-core</artifactId>
            <version>1.32</version>
        </dependency>
        <dependency>
            <groupId>com.github.wxiaoqi</groupId>
            <artifactId>jwt-core</artifactId>
            <version>4.0-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>com.google.guava</groupId>
            <artifactId>guava</artifactId>
            <version>20.0</version>
        </dependency>
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-webmvc</artifactId>
            <version>4.3.9.RELEASE</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>com.netflix.feign</groupId>
            <artifactId>feign-core</artifactId>
            <version>8.18.0</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>com.netflix.hystrix</groupId>
            <artifactId>hystrix-core</artifactId>
            <version>1.5.12</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>javax.validation</groupId>
            <artifactId>validation-api</artifactId>
            <version>1.1.0.Final</version>
        </dependency>
        <dependency>
            <groupId>org.springframework.security</groupId>
            <artifactId>spring-security-core</artifactId>
            <version>4.2.3.RELEASE</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>io.swagger</groupId>
            <artifactId>swagger-annotations</artifactId>
            <version>1.5.13</version>
            <scope>provided</scope>
        </dependency>
        
        <dependency>
            <groupId>com.grouppower</groupId>
            <artifactId>id-generator</artifactId>
            <version>0.0.1-SNAPSHOT</version>
        </dependency>

    </dependencies>

**代码如下:**
        Page<Resume> page = PageHelper.startPage(1, 2);
        Example example = new Example(Resume.class);
        example.createCriteria().andLike(Resume.ID, "%" + "1" + "%");
        List<Resume> resumes = mapper.selectByExample(example);
        return new TableResultResponse<>(page.getTotal(), resumes);

**日志如下:**
2018-10-16 09:51:01.286 DEBUG  [  XNIO-2 task-2] selectByExample                          159 : ==>  Preparing: SELECT id, is_deleted, recruitment_channel, tag FROM resume WHERE (id LIKE ?) 
2018-10-16 09:51:01.287 DEBUG  [  XNIO-2 task-2] selectByExample                          159 : ==> Parameters: %1%(String)
2018-10-16 09:51:01.293 DEBUG  [  XNIO-2 task-2] selectByExample                          159 : <==      Total: 3

**Comment by 84yy** [comment]
补充一下:我使用相同的依赖新建一个项目后,执行上面问题描述中相同的操作,是可以实现分页的,我怀疑是pagehelp跟我项目中的某些依赖冲突了.

**Comment by abel533** [comment]
在分页插件中断点看看有没有进去。

**Comment by 84yy** [comment]
> 在分页插件中断点看看有没有进去。
断点不会进去....

**Comment by 84yy** [comment]
configuration.addInterceptor(new MybatisDataInterceptor_new(userDepartDataService));
        configuration.addInterceptor(new PageInterceptor());我手动把分页拦截器加到拦截链上来可以进入分页拦截器了,目前是报dialect空指针异常,估计是拦截器参数也要手动设置现在,我自己先试试.

**Comment by 84yy** [comment]
中午回来,再更新一下我的查错进度,供后面的朋友参考:
目前的配置;
import com.github.pagehelper.PageInterceptor;
import com.github.pagehelper.autoconfigure.PageHelperProperties;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.context.properties.EnableConfigurationProperties;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;


@EnableConfigurationProperties(PageHelperProperties.class)
@Configuration
public class PageInterceptorConfig {


    @Autowired
    private PageHelperProperties properties;

    @Bean
    public PageInterceptor pageInterceptor() {
        PageInterceptor pageInterceptor = new PageInterceptor();
        pageInterceptor.setProperties(properties.getProperties());
        return pageInterceptor;
    }
}

============================华丽分割线==============================
============================华丽分割线==============================

import com.github.pagehelper.PageInterceptor;
import com.grouppower.security.common.data.IUserDepartDataService;
import com.grouppower.security.common.data.MybatisDataInterceptor_new;
import org.apache.ibatis.session.SqlSessionFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Configuration;

import javax.annotation.PostConstruct;

/**
 * 租户 \ 部⻔门数据隔离
 */
@Configuration
public class MybatisDataConfig {

    @Autowired
    private SqlSessionFactory sqlSessionFactory;

    @Autowired
    private PageInterceptor pageInterceptor;

    /**
     * 该⽅方法主要是为了了让当前⽤用户可以获取授权的数据权限部⻔门
     */
    @Autowired
    private IUserDepartDataService userDepartDataService;

    @PostConstruct
    public void init() {
        org.apache.ibatis.session.Configuration configuration = sqlSessionFactory.getConfiguration();
        configuration.addInterceptor(new MybatisDataInterceptor_new(userDepartDataService));
        configuration.addInterceptor(pageInterceptor);
    }
}


启动没报错,执行以上相同的查询,目前报错;
_**Caused by: org.apache.ibatis.exceptions.PersistenceException: 
### Error querying database.  Cause: java.lang.RuntimeException: 在系统中发现了多个分页插件，请检查系统配置!
### Cause: java.lang.RuntimeException: 在系统中发现了多个分页插件，请检查系统配置!**_

**Comment by 84yy** [comment]
参考这个答案上面的做法,在springboot启动类排除插件自带的配置类
https://github.com/pagehelper/pagehelper-spring-boot/issues/18
### **结果未能解决问题**
郁闷啊,而且实际调试中PageHelperAutoConfiguration这个类还是会被注入到容器的

**Comment by 84yy** [comment]
if(ms.getId().endsWith(MSUtils.COUNT)){
            throw new RuntimeException("在系统中发现了多个分页插件，请检查系统配置!");
}
这一步报错,生成的查询也被拦截了

com.grouppower.candidate.mapper.ResumeMapper.selectByExample_COUNT

**Comment by 84yy** [comment]
仍然无法解决问题，总结下来就是当我重新定义 sqlSessionFactory ,自定义添加 pageInteceptor 时会造成在系统中发现了多个分页插件的报错，如果不手动添加pageInteceptor，则拦截器不起作用

**Comment by 84yy** [comment]
总算解决了,我的天!!!
参考这个答案https://blog.csdn.net/li_tianchang/article/details/81450849
第一种方法我不起作用,第二种方法起作用了.
