### ISSUE TITLE
数据库Teradata和Hana是否支持

### ISSUE THREAD

**Issue by Abandoner** [pagehelper/pagehelper-spring-boot#67]
现有的版本中是否支持天睿的Teradata 和 SAP的Hana 数据库?

**Comment by szcgit1** [comment]
Teradata: 
url:jdbc:teradata://192.168.0.103/DATABASE=packfdv5,TMODE=TERA,CHARSET=UTF8,DBS_PORT=1025
分页sql:
select DatabaseName ,
TableName,
row_number() OVER (ORDER BY DatabaseName,TableName) rn
 from DBC.Tables t2
 order by DatabaseName,TableName  qualify rn<= 3 ;

**Comment by abel533** [comment]
@szcgit1 直接来个PR :+1:
