### ISSUE TITLE
能不能升级一下mybatis的版本

### ISSUE THREAD

**Issue by cschenzz** [pagehelper/pagehelper-spring-boot#68]
mybatis的3.5.0版本已经出来了,现在的版本还是基于3.4.6
最近我再使用mybatis-plus集成时,出现类无法加载问题,经分析,是由于mp和pagehelper都使用与mybatis库,并且mp最新版用的是3.5.0,而pagehelper用的是3.4.6而导致了版本冲突

希望作者能升级版本并推送到maven仓库

**Comment by cschenzz** [comment]
试过冲突的解决的办法,但还是报错,暂时只能回退到以前版本

**Comment by gh6497** [comment]
同求呀,老哥

**Comment by cschenzz** [comment]
没反应哪,作者是不是不维护这个项目了?

**Comment by abel533** [comment]
明天发布新版本。
