### ISSUE TITLE
查询总记录数的时候，会查询全表

### ISSUE THREAD

**Issue by curdlx** [pagehelper/pagehelper-spring-boot#7]
您好，我发现查询总记录数的时候，会查询全表，这效率很低啊

**Comment by abel533** [comment]
会不会查询全表和你条件有关，欢迎提供更好的方式。

**Comment by curdlx** [comment]
是的，我看了下源码，是jsqlparser没能解析出我的sql，执行了SimpleCountSql。改了一下sql就好了，这样很好，谢谢

**Comment by curdlx** [comment]
是的，我看了下源码，是jsqlparser没能解析出我的sql，执行了SimpleCountSql。改了一下sql就好了，这样很好，谢谢

**Comment by abel533** [comment]
不客气。
