### ISSUE TITLE
【求助】SpringBoot 2.1.0.RELEASE配置后没有执行分页操作返回所有数据

### ISSUE THREAD

**Issue by PanBY** [pagehelper/pagehelper-spring-boot#71]
SpringBoot 2.1.0.RELEASE
pagehelper-spring-boot-starter 1.2.10
mybatis-spring-boot-starter 2.0.0
没有手动配置项

Service代码为
    public List<COrder> getTodayAllOrder(Integer agentId, Integer pageSize, Integer pageNum) {
        COrderExample cOrderExample = new COrderExample();
        cOrderExample.createCriteria().andSenderEqualTo(agentId);
        //criteria.andCreateTimeBetween(DateUtils.getDayBegin(),DateUtils.getDayEnd());
        PageHelper.startPage(pageNum, pageSize);
        List<COrder> cOrderList = cOrderMapper.selectByExample(cOrderExample);
        return cOrderList;
    }
Controller为
    public Object getTodayAllOrderPageByAgentId(Integer agentId,
                                                @RequestParam(value = "pageSize", defaultValue = "5") Integer pageSize,
                                                @RequestParam(value = "pageNum", defaultValue = "1") Integer pageNum){
        List<COrder> todayAllOrderList = orderService.getTodayAllOrder(agentId, pageSize, pageNum);
        PageInfo<COrder> cOrderPageInfo = new PageInfo<COrder>(todayAllOrderList);
        return new CommonResult().success(cOrderPageInfo);
    }

传入分页为pageSize 1，pageNum 1
最终返回所有内容为46条数据
请问各位大神这个为什么啊 网上搜了好多文章配置都不对

**Comment by lpc123456** [comment]
我也是遇到这样的问题

**Comment by zzl1787** [comment]
Me, too.

**Comment by PanBY** [comment]
后来找到原因解决了 详见博客https://blog.csdn.net/mmlik8878/article/details/88322723

**Comment by PanBY** [comment]
> Me, too.

后来找到原因解决了 详见博客https://blog.csdn.net/mmlik8878/article/details/88322723

**Comment by smfx1314** [comment]
我的也是

**Comment by littlecurl** [comment]
俺也一样！

**Comment by miaoxiake** [comment]
https://blog.csdn.net/qq_38217237/article/details/89061751?utm_source=app



---原始邮件---
发件人: "LittleCurl"<notifications@github.com&gt;
发送时间: 2020年1月27日(周一) 晚上9:35
收件人: "pagehelper/pagehelper-spring-boot"<pagehelper-spring-boot@noreply.github.com&gt;;
抄送: "Comment"<comment@noreply.github.com&gt;;"miaoxiake"<852297586@qq.com&gt;;
主题: Re: [pagehelper/pagehelper-spring-boot] 【求助】SpringBoot 2.1.0.RELEASE配置后没有执行分页操作返回所有数据 (#71)



俺也一样！

**Comment by littlecurl** [comment]
> 俺也一样！

原来是我用错方式了?
我最终解决方式如下:
原先的分页代码:

        PageHelper.startPage(1,1);
        List<UserModel> userModelList = userService.getUserListByPage();
        PageInfo<UserModel> userModelPageInfo = new PageInfo<>(userModelList);
改为现在的:

        Page page = PageHelper.startPage(1,1);
        List<UserModel> userModelList = userService.getUserListByPage();
        PageInfo<UserModel> userModelPageInfo = page.toPageInfo();
这样得到的PageInfo数据都是正确的.
