### ISSUE TITLE
PageInterceptor中countMsId的生成逻辑应该能支持自定义

### ISSUE THREAD

**Issue by zhangxb1987** [pagehelper/pagehelper-spring-boot#77]

**Comment by zhangxb1987** [comment]
目前：String countMsId = msId + countSuffix; 这种方案写死了，这里如果能提供接口回调就好了。

**Comment by abel533** [comment]
新版本：

4. `countMsIdGen`（5.3.2+）：count 方法的 msId 生成方式，默认是 查询的 msId +
   countSuffix，想要自己定义时，可以实现 `com.github.pagehelper.CountMsIdGen` 接口，将该参数配置为实现的全限定类名即可。
   **一个常见的用途：** 在有Example查询的情况，`selectByExample` 可以使用对应的 `selectCountByExample` 方法进行 count 查询。
