### ISSUE TITLE
引入pagehelper-spring-boot-starter启动时报错

### ISSUE THREAD

**Issue by gcluo** [pagehelper/pagehelper-spring-boot#8]
springboot version: 2.0
.yml文件
spring:
    dataSource:
        name: test
        url: jdbc:mysql://127.0.0.1:3306/cy_qydb?useUnicode=true&amp;characterEncoding=utf8&amp;useSSL=false
        username: root
        password: 123456
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 100
        initialSize: 50
        maxWait: 10000
        minIdle: 50
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 30000
        validationQuery: SELECT 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20

mybatis:
    config-location: classpath:mybatis-config.xml
    mapper-locations: classpath:mapper/*.xml

pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
与mybatis相关的插件
compile('com.alibaba:druid:1.0.25')
compile('org.mybatis:mybatis-typehandlers-jsr310:1.0.1')
compile('mysql:mysql-connector-java:5.1.39')
compile('org.mybatis:mybatis:3.4.1')
compile('org.mybatis:mybatis-spring:1.3.0')
compile('org.mybatis.spring.boot:mybatis-spring-boot-starter:1.3.0')
compile('com.github.pagehelper:pagehelper:5.0.0')
compile('com.github.pagehelper:pagehelper-spring-boot-starter:1.1.1')

错误信息
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'com.github.pagehelper.autoconfigure.PageHelperAutoConfiguration': Post-processing of merged bean definition failed; nested exception is java.lang.IllegalStateException: Failed to introspect Class [com.github.pagehelper.autoconfigure.PageHelperAutoConfiguration] from ClassLoader [org.springframework.boot.loader.LaunchedURLClassLoader@1c20c684]

**Comment by abel533** [comment]
1.0.0版本可能在低版本的springboot上会出现这个错误，用最新的pagehelper-starter试试。

**Comment by gcluo** [comment]
是spring boot 2.0 取消了RelaxedPropertyResolver这个类，所以会报错，回滚spring boot 版本到1.4.x就可以了。

**Comment by abel533** [comment]
我尽快做2.0的兼容。

**Comment by gm100861** [comment]
现在做好兼容了吗?我也遇到这个错误了.

**Comment by abel533** [comment]
@gm100861 最新版本没问题。

**Comment by abel533** [comment]
Spring boot 极个别版本有问题，其中就有 1.5.1.。。换个中间数或者 1.5.x 的最新版本。

**Comment by z778856** [comment]
现在看来新版本解决了这个问题
