### ISSUE TITLE
page-size-zero无效

### ISSUE THREAD

**Issue by liunaijie** [pagehelper/pagehelper-spring-boot#81]
在配置文件中配置上
```
pagehelper:
  page-size-zero: true
```
理应传入页码为0时显示全部数据，但是配置无效，传入0时还是第一页的数据，使用的默认设置即此配置没有生效。  
然后我又调用`PageHelper.startPage(page, 10, true, null, true);`手动调用方法并声明pageSizeZero生效，但是还是不起作用。
![image](https://user-images.githubusercontent.com/28497357/61435730-cb5d6080-a96b-11e9-9a10-dfd6332a5d02.png)

**Comment by Rebuilding127** [comment]
遇到同样问题，有解决吗？

**Comment by abel533** [comment]
pageSize 和 pageNum 搞混了吧。
