### ISSUE TITLE
pagehelper.autoRuntimeDialect = true时，获取方言可能存在bug

### ISSUE THREAD

**Issue by Burt-L** [pagehelper/pagehelper-spring-boot#87]
版本：
spring-boot:2.0.3
pagehelper-spring-boot-starter:1.2.12
sharding-jdbc-spring-boot-starter:3.1.0
druid-spring-boot-starter:1.1.20

配置：
pagehelper.helperDialect=sqlserver2012
pagehelper.reasonable=false
pagehelper.supportMethodsArguments=true
pagehelper.params=count=countSql
pagehelper.pageSizeZero=true
pagehelper.autoRuntimeDialect = true

描述：
当pagehelper.autoRuntimeDialect = true时，会通过jdbc url动态获取方言，即通过方法 com.github.pagehelper.page.PageAutoDialect#getUrl 获取url。当使用sharding-jdbc的主从模式时，DataSource实际类型为MasterSlaveDataSource，第178行conn.getMetaData().getURL();如果该连接已被关闭，则会抛异常（异常信息：该连接已关闭。）（MasterSlaveDataSource获取连接时不会像DruidDataSource一样先检测该连接是否已关闭）。

**Comment by Burt-L** [comment]
如果我这边要改成只适应我的业务的话，我可以判断一下getUrl时的DataSource的类型就好了。但是要改成通用的，我暂时还没想到什么好办法。

**Comment by abel533** [comment]
指定数据库，别自动获取。

**Comment by Burt-L** [comment]
尴尬的是，我这边的业务会mysql sqlserver一起使用
