### ISSUE TITLE
1.2.12版本net.sf.jsqlparser.statement.select.PlainSelect.getGroupBy()

### ISSUE THREAD

**Issue by farawayll** [pagehelper/pagehelper-spring-boot#91]
1.2.12版本
`
PageHelper.offsetPage(pageNum,pageSize);
List<Card> cards = cardMapper.queryAllByLimit();
return new PageInfo<Card>(cards);
`
报错net.sf.jsqlparser.statement.select.PlainSelect.getGroupBy()
退回上一版本正常

**Comment by abel533** [comment]
完整错误是什么？
