### ISSUE TITLE
Oracle分页百万以上太慢了

### ISSUE THREAD

**Issue by Tarems** [pagehelper/pagehelper-spring-boot#98]
分页语句200ms
`SELECT * FROM ( SELECT PAGEABLE_.*,ROWNUM ROW_ID FROM ( SELECT * from w_encu WHERE CHECK_TIME between to_date(?,'yyyy-mm-dd HH24:mi:ss') and to_date(?,'yyyy-mm-dd HH24:mi:ss')  order by CHECK_TIME desc ) PAGEABLE_ WHERE ROWNUM <= 20) WHERE ROW_ID > 0`

**建议优化一下
pagehelper-spring-boot-starter版本>=1.2.7 开始使用的是下面的语句**
pagehelper的分页语句5s
`SELECT * FROM ( SELECT TMP_PAGE.*, ROWNUM ROW_ID FROM ( SELECT * FROM w_encu WHERE CHECK_TIME BETWEEN to_date(?, 'yyyy-mm-dd HH24:mi:ss') AND to_date(?, 'yyyy-mm-dd HH24:mi:ss') order by CHECK_TIME desc ) TMP_PAGE) WHERE ROW_ID <= 20 AND ROW_ID > 0`

**Comment by xieisabug** [comment]
在分页数巨大的情况下，上面那个sql一样很慢。
感觉这个情况得自己写更优化的sql了，pagehelper这种很难做统一的优化

**Comment by Tarems** [comment]
> 在分页数巨大的情况下，上面那个sql一样很慢。
> 感觉这个情况得自己写更优化的sql了，pagehelper这种很难做统一的优化

那倒是,,目前已经在数据库方面解决了

**Comment by Tarems** [comment]
> 在分页数巨大的情况下，上面那个sql一样很慢。
> 感觉这个情况得自己写更优化的sql了，pagehelper这种很难做统一的优化

那倒是,,目前已经在数据库方面解决了
